### ISSUE TITLE
race conditions

### ISSUE THREAD

**Issue by max-degterev** [artsy/sharify#14]
Hey guys, we have a similar implementation and noticed that if you have a big number of concurrent requests they overlap.

Ex:

Request 1 resets shared data, sets var A to be 'X'
Request 2 resets shared data, sets var A to be 'Y'

In another file we require sharify again.
Request 1 reads shared data, expects to A==='X', gets A==='Y' ==> FAIL
Request 2 reads shared data, expects to A==='Y', gets A==='Y' ==> OK

Any ideas how to overload module exports so it works per-request?

**Comment by craigspaeth** [comment]
Thanks for using sharify! Beyond the initial constant data you inject in sharify you shouldn't be injecting directly into `require('sharify').data` or you will get these race conditions. To inject request-level data follow the [Bootstrapping Request-level Data to the Client](https://github.com/artsy/sharify#bootstrapping-request-level-data-to-the-client) tldr; use `res.locals.sharify.data.FOO = 'bar'` instead of `sharify.data.FOO = 'bar'`.

Hope that helps! Feel free to reopen if I'm missing something.

**Comment by max-degterev** [comment]
Dam, thats what I came up with as well. I hoped there's a better way. Basically renders sharfy useless if you want to fetch stuff on the server and then pass json to the client to restore models etc.

Thanks!

**Comment by craigspaeth** [comment]
Hmm maybe I'm missing something, but isn't that what [the example](https://github.com/artsy/sharify#bootstrapping-request-level-data-to-the-client) is showing? We do that all the time at Artsy e.g.

Server:

``` javascript
var Artwork = require('../models/artwork');

app.get('/artwork/:id', function(req, res) {
  new Artwork({ id: req.params.id }).fetch({
    success: function(artwork) {
      res.locals.sharify.data = artwork.toJSON();
      res.render('artwork-page');
    });
  });
});
```

Client:

``` javascript
var Artwork = require('../models/artwork');
var ARTWORK = require('sharify').data.ARTWORK;

var artwork = new Artwork(ARTWORK);
$('h1').html(artwork.get('title'));
```

I would be happy to help figure out your use case if you want to copy/paste some code samples.

**Comment by max-degterev** [comment]
No, you got me wrong. I meant I didn't like assigning it on request :) The way you show surely works!

**Comment by craigspaeth** [comment]
Ah, I see. I'm not sure if there's a way around assigning it on the request, but I'm open to ideas.  :smile_cat:
